### ISSUE TITLE
add provider时报错

### ISSUE THREAD

**Issue by jiaoyilun** [jyqq163/keycloak-services-social-weixin#1]
你好，我打包加入项目，控制台执行了热部署，在界面上add provider时报错，你这边遇到过吗
`ERROR [io.undertow.request] (default task-8) UT005023: Exception handling request to /auth/admin/realms/MyApp/identity-provider/providers/weixin: java.lang.NoClassDefFoundError: Failed to link org/keycloak/social/weixin/WeiXinIdentityProvider (Module "deployment.keycloak-services-social-weixin-0.0.2.jar" from Service Module Loader): org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:839)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)`

**Comment by jyqq163** [comment]
方便说下你keycloak 版本吗？我这是基于keycloak-4.1.0.Final 版本开发的

**Comment by jyqq163** [comment]
> 你好，我打包加入项目，控制台执行了热部署，在界面上add provider时报错，你这边遇到过吗
> `ERROR [io.undertow.request] (default task-8) UT005023: Exception handling request to /auth/admin/realms/MyApp/identity-provider/providers/weixin: java.lang.NoClassDefFoundError: Failed to link org/keycloak/social/weixin/WeiXinIdentityProvider (Module "deployment.keycloak-services-social-weixin-0.0.2.jar" from Service Module Loader): org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:763) at java.lang.ClassLoader.defineClass(ClassLoader.java:839) at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424) at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519) at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339) at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126) at org.jboss.modules.Module.loadModuleClass(Module.java:731) at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247) at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410) at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398) at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116) at java.lang.Class.forName0(Native Method)`

方便说下你keycloak 版本吗？我这是基于keycloak-4.1.0.Final 版本开发的

**Comment by jyqq163** [comment]
经过测试5.0版本依然支持
![image](https://user-images.githubusercontent.com/10881628/55377050-d4a1f900-5545-11e9-8baf-b9def87823c4.png)

**Comment by jiaoyilun** [comment]
> 经过测试5.0版本依然支持
> ![image](https://user-images.githubusercontent.com/10881628/55377050-d4a1f900-5545-11e9-8baf-b9def87823c4.png)

你好，方便留个联系方式吗，请教下

**Comment by jiaoyilun** [comment]
我这是官网下载的5.0版本，解压，直接单机模式启动，没找到您说的两个目录，就把jar扔到了 deployment文件夹下，看到日志热加载了文件，不知道您是怎么操作的，能否指点下，方便留个联系方式吗，

**Comment by jyqq163** [comment]
> 我这是官网下载的5.0版本，解压，直接单机模式启动，没找到您说的两个目录，就把jar扔到了 deployment文件夹下，看到日志热加载了文件，不知道您是怎么操作的，能否指点下，方便留个联系方式吗，
![image](https://user-images.githubusercontent.com/10881628/55380958-631d7700-5554-11e9-8b99-87a15ffd48f7.png)

手动创建该文件夹，然后放入jar即可.还有其他问题可微信搜索phantom_Dream

**Comment by jiaoyilun** [comment]
已解决，谢谢
